language: r
cache: packages


r:
  - oldrel
  - release
  - devel

apt_packages:
  - libgsl0-dev
  - libnlopt-dev
  - devscripts

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
