language: r
cache: packages
sudo: required

r:
  - oldrel
  - release
  - devel

apt_packages:
  - libgsl0-dev
  - libnlopt-dev

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
