---
title: "smam: Statistical Modeling for Animal Movements"
author: "Chaoran Hu"
fontsize: 12pt
documentclass: article
margin: 1in
output: pdf_document
---

#1. Introduction

This package is designed for animal movement analysis. We totally implemented
three models, Brownian motion with measurement error, moving-resting process
with embedded Brownian motion [2,3], and moving-resting-hunting process with embedded
Brownian motion [1]. We also provided toolbox for seasonal analysis within this
package, because wild animal usually has obvious seasonal behavior.

In this vignette, we play with a mountain lion GPS dataset and quantify the
movement behavior of lion. First of all, let us take a look at the dataset.

```{r, include=FALSE}
load("/Users/ChaoranHu/Desktop/thmam_project/lionData/dataset/lionData.RData")
```


















# References
[1] Pozdnyakov, V., Elbroch, L., Hu, C., Meyer, T., and Yan, J. (2018+) On estimation for
Brownian motion governed by telegraph process with multiple off states. Under Review.

[2] Pozdnyakov, V., Elbroch, L., Labarga, A., Meyer, T., and Yan, J. (2017) Discretely
observed Brownian motion governed by telegraph process: estimation. Methodology and
Computing in Applied Probability. To Appear.

[3] Yan, J., Chen, Y., Lawrence-Apfel, K., Ortega, I. M., Pozdnyakoc, V., Williams, S., and
Meyer, T. (2014) A moving-resting process with an embedded Brownian motion for animal
movements. Population Ecology. 56(2): 401--415.




