# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vp11 <- function(vw, t, lambda1, lambda0) {
    .Call('_smam_vp11', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp10 <- function(vw, t, lambda1, lambda0) {
    .Call('_smam_vp10', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp00 <- function(vw, t, lambda1, lambda0) {
    .Call('_smam_vp00', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp01 <- function(vw, t, lambda1, lambda0) {
    .Call('_smam_vp01', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

h11 <- function(x, t, theta, integrControl) {
    .Call('_smam_h11', PACKAGE = 'smam', x, t, theta, integrControl)
}

h10 <- function(x, t, theta, integrControl) {
    .Call('_smam_h10', PACKAGE = 'smam', x, t, theta, integrControl)
}

h00 <- function(x, t, theta, integrControl) {
    .Call('_smam_h00', PACKAGE = 'smam', x, t, theta, integrControl)
}

h01 <- function(x, t, theta, integrControl) {
    .Call('_smam_h01', PACKAGE = 'smam', x, t, theta, integrControl)
}

ncllk_m1_inc <- function(theta, data, integrControl, logtr) {
    .Call('_smam_ncllk_m1_inc', PACKAGE = 'smam', theta, data, integrControl, logtr)
}

nllk_inc <- function(theta, data, integrControl, logtr) {
    .Call('_smam_nllk_inc', PACKAGE = 'smam', theta, data, integrControl, logtr)
}

fwd_bwd_mr <- function(theta, data, integrControl) {
    .Call('_smam_fwd_bwd_mr', PACKAGE = 'smam', theta, data, integrControl)
}

viterbi_mr <- function(theta, data, integrControl) {
    .Call('_smam_viterbi_mr', PACKAGE = 'smam', theta, data, integrControl)
}

partial_viterbi_mr <- function(theta, data, integrControl, startpoint, pathlength) {
    .Call('_smam_partial_viterbi_mr', PACKAGE = 'smam', theta, data, integrControl, startpoint, pathlength)
}

fwd_bwd_ths <- function(theta, data, integrControl) {
    .Call('_smam_fwd_bwd_ths', PACKAGE = 'smam', theta, data, integrControl)
}

viterbi_ths <- function(theta, data, integrControl) {
    .Call('_smam_viterbi_ths', PACKAGE = 'smam', theta, data, integrControl)
}

partial_viterbi_ths <- function(theta, data, integrControl, startpoint, pathlength) {
    .Call('_smam_partial_viterbi_ths', PACKAGE = 'smam', theta, data, integrControl, startpoint, pathlength)
}

ths_vp00 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp00', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp01 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp01', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp02 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp02', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp10 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp10', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp11 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp11', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp12 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp12', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp20 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp20', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp21 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp21', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_vp22 <- function(vs, t, lambda0, lambda1, lambda2, p) {
    .Call('_smam_ths_vp22', PACKAGE = 'smam', vs, t, lambda0, lambda1, lambda2, p)
}

ths_h00 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h00', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h01 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h01', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h02 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h02', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h10 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h10', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h11 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h11', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h12 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h12', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h20 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h20', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h21 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h21', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h22 <- function(x, t, theta, integrControl) {
    .Call('_smam_ths_h22', PACKAGE = 'smam', x, t, theta, integrControl)
}

ths_h00_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h00_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h01_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h01_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h02_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h02_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h10_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h10_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h11_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h11_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h12_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h12_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h20_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h20_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h21_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h21_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

ths_h22_paral <- function(x, t, theta, integrControl, grainSize) {
    .Call('_smam_ths_h22_paral', PACKAGE = 'smam', x, t, theta, integrControl, grainSize)
}

con_v_m <- function(x) {
    .Call('_smam_con_v_m', PACKAGE = 'smam', x)
}

con_n_v <- function(x) {
    .Call('_smam_con_n_v', PACKAGE = 'smam', x)
}

nllk_fwd_ths <- function(theta, data, integrControl) {
    .Call('_smam_nllk_fwd_ths', PACKAGE = 'smam', theta, data, integrControl)
}

nllk_fwd_ths_parallel <- function(theta, data, integrControl, grainSize) {
    .Call('_smam_nllk_fwd_ths_parallel', PACKAGE = 'smam', theta, data, integrControl, grainSize)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_smam_RcppExport_registerCCallable', PACKAGE = 'smam')
})
